// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.Hand = (function(superClass) {
  extend(Hand, superClass);

  function Hand() {
    return Hand.__super__.constructor.apply(this, arguments);
  }

  Hand.prototype.model = Card;

  Hand.prototype.initialize = function(array, deck, isDealer) {
    this.deck = deck;
    this.isDealer = isDealer;
  };

  Hand.prototype.hit = function() {
    this.add(this.deck.pop());
    if (this.scores()[0] > 21) {
      return $('body').css({
        'background-color': 'red'
      });
    }
  };

  Hand.prototype.hasAce = function() {
    return this.reduce(function(memo, card) {
      return memo || card.get('value') === 1;
    }, 0);
  };

  Hand.prototype.minScore = function() {
    return this.reduce(function(score, card) {
      return score + (card.get('revealed') ? card.get('value') : 0);
    }, 0);
  };

  Hand.prototype.scores = function() {
    return [this.minScore(), this.minScore() + 10 * this.hasAce()];
  };

  Hand.prototype.stand = function() {
    return this.dealerTurn();
  };

  Hand.prototype.dealerTurn = function() {
    this.at(0).flip();
    while (this.scores()[0] <= 16 && this.scores()[1] <= 16) {
      this.add(this.deck.pop());
    }
    if (this.scores()[1] < 22) {
      return this.trigger('endGame');
    } else {
      while (this.scores()[0] <= 16) {
        this.add(this.deck.pop());
      }
      if (this.scores()[0] < 22) {
        return this.trigger('endGame');
      } else {
        return $('body').css({
          'background-color': 'lightgreen'
        });
      }
    }
  };

  Hand.prototype.newGame = function() {
    return this.trigger('newGame');
  };

  return Hand;

})(Backbone.Collection);
