// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.CardView = (function(superClass) {
  extend(CardView, superClass);

  function CardView() {
    return CardView.__super__.constructor.apply(this, arguments);
  }

  CardView.prototype.className = 'card';

  CardView.prototype.template = _.template('<img height=142 width=102 src="../2015-06-blackjack/img/cards/<%= rankName %>-<%= suitName %>.png">');

  CardView.prototype.initialize = function() {
    return this.render();
  };

  CardView.prototype.render = function() {
    this.$el.addClass('covered');
    if (this.model.get('revealed')) {
      this.$el.removeClass('covered');
      return this.$el.html(this.template(this.model.attributes));
    }
  };

  return CardView;

})(Backbone.View);
